### PR TITLE
Combine all action scripts into one

### PR DESCRIPTION
**Pull request by Tyilo**
As discussed in #27.

### CODE REVIEW

**Comment by caleb531** [comment]
The filter scripts need to be modified to pass input to the action script in the form of `{type}-{value}`. Currently, only the value is passed.

**Comment by Tyilo** [comment]
Oh yeah I updated the scripts in the `.alfredworkflow` file, but not in the `.applescript` files.

**Comment by caleb531** [comment]
Really? Because I discovered the issue when running the workflow file itself.

When I try to play a song, the Alfred debugger returns the following log message:
```
Unknown type: 1333
```

I'm fairly confident that 1333 is the ID of the song I'm trying to play. I believe that there is some flaw in the type/value-parsing logic you added.

**Comment by Tyilo** [comment]
Yeah but that what because I did the following:

* Edited the files in Afred and confirmed they worked
* Updated the action file
* Ran the python script, which then overwrited the files inside the `.afredworkflow`

It should be fixed now, however.

**Comment by caleb531** [comment]
Well, would you look at that! It works now. :P

As I said, everything looks good. I'll merge this in and create a new release when I have some time to spare.

**Pull request merged**
