### PR TITLE
Fix script compilation issue for synced Alfred installs

### PR DESCRIPTION
**Pull request by caleb531**
@Tyilo, I have an interesting issue to discuss with you.

I recently got a new MacBook Pro to replace the one I use in addition to my iMac. After adding a few songs from my iMac's iTunes library to the library for my new MacBook, Play Song seemed to stop working on my new MacBook (the results would never show).

After much experimentation, I discovered that (seemingly) `config.scpt` could *only* be loaded by the workflow *if* that configuration file was compiled on the same Mac. This seemed very odd to me, because I had two Macs before, and I never had this issue. *Perhaps* because my new Mac is a newer model, there is some difference in architecture or software that affects how AppleScripts are compiled/executed.

To solve this issue, I've modified `compile-config.sh` to compile the configration to a different location, and I've updated the filter/action scripts to account for this change. The compile script now saves `config.scpt` to Alfred's local workflow cache.  It also copies `config.applescript` to the cache as well, so it can be compared with the installed copy of the configuration file (this allows for new versions of the workflow to recognize changes to the configuration).

As for the changes to the filter/action scripts, you'll notice that I moved the configuration-loading logic into a separate handler. I realize that this makes the codebase slightly less DRY, and so I was curious if you'd like to implement a new syntax for inserting that loading logic when running `update-workflow.py` (`@include: load-config@`, perhaps, assuming `load-config.applescript` exists in the repository somewhere). We could potentially expand this syntax into a sort of preprocessing directive (`@include: foo`), but then I fear we might be making the workflow overly complex. Would be interested in hearing your thoughts.

Thanks, and Happy New Year. :)
Caleb

### CODE REVIEW

**Comment by Tyilo** [comment]
Instead of copying the `config.applescript` over to the cache to detect changes, wouldn't it be better to just store a unix timestamp for when `config.scpt` was last compiled and compare that with the modification time of `config.applescript`? Alternatively a hash could be stored instead of a timestamp.

I think implementing `@include` might be overkill, but I might implement it later if I feel like it.

**Comment by caleb531** [comment]
I'm not sure I like the last-modified approach, because last-modified dates (LMDs) can be too easily changed. For instance, my editor touches files on save (thus updating the LMD) even though the contents haven't changed. If Git doesn't think about file changes in that way, I wouldn't prefer to, either.

I also thought about the hash approach, but it seemed easier and technically faster (or more efficient) to compare the contents rather than compute the hashes and then compare them. Remember, this script needs to run on every keystroke (which is as often as the filter script is called). Therefore, the script's performance is a priority for me.

**Comment by Tyilo** [comment]
Here's a speed comparison by using your `compile-config.sh` and two versions of the script using either md5 or sha1 to hash the file:
```
$ time bash -c 'seq 100 | xargs -n 1 bash old-compile-config.sh' # Comparing directly
        1.29 real         0.59 user         0.63 sys
$ time bash -c 'seq 100 | xargs -n 1 bash md5-compile-config.sh' # Using hash
        0.96 real         0.37 user         0.50 sys
$ time bash -c 'seq 100 | xargs -n 1 bash sha1-compile-config.sh' # Using hash
        4.02 real         2.83 user         0.91 sys
```

As you can see calculating an md5 sum and comparing it with a saved one is actually faster than comparing two `config.applescript`.

**Comment by Tyilo** [comment]
I think both this and #18 should be merged too.

**Pull request merged**
