### PR TITLE
Drop "contains" logic for finding matching results

### PR DESCRIPTION
**Pull request by caleb531**
Hi, @Tyilo. I have an idea for a change to Play Song's searching algorithm, though I wanted to ask you about it first.

## Proposal

Currently, Alfred groups results into one of three categories:

1. Results whose names begin with the query
2. Results whose names contain a word that begins with the query
3. Results whose names contain the query, regardless of position

I am essentially proposing that we drop the third rule when finding relevant results.

## Rationale

* People's search terms almost always reflect the beginning of a phrase or beginning of a word within that phrase
    * I can't think of a single instance in which it is practical to search for a phrase that is in the middle or at the end of a word
* Dropping this third rule should improve Alfred's efficiency (and possibly performance) in finding results
    * Doing so should also eliminate the longest of the three result-retrieving lines within the `findResults()` handler

What do you think?

### CODE REVIEW

**Comment by caleb531** [comment]
I discovered (the hard way) that removing the "contains" logic would cause words enclosed in quotes not to be matched. Therefore, I have decided to cancel these changes.

**Comment by Tyilo** [comment]
Ok :(

**Comment by caleb531** [comment]
Reopening this issue—I have a better idea. ;)

Rather than dropping the "contains" logic entirely, the "contains" search will only be executed if the result list is empty at that point. In addition, I would add a few if statements to ensure that subsequent searches (i.e. `get every track...`) are only executed if the number of results in the result list is within the defined limit. This should be guaranteed to work and not truncate relevant results, because with this new logic that we agreed upon, that list of tracks is always sorted properly.

Thoughts?

**Comment by Tyilo** [comment]
Seems good to me.

**Pull request merged**
